version: "3.9"
services:
  mfnuxt:
    container_name: mfnuxt
    build: .
    environment:
      - VIRTUAL_HOST=mfnuxt
    networks:
      - mf_proxy
    volumes:
      - .:/app
      - /node_modules
    ports:
      - 3000:3000
networks:
  mf_proxy:
    external:
      name: mf_proxy
