version: "3.9"
services:
  mf_nuxt:
    container_name: mf_nuxt
    image: node:18.15.0-alpine3.17
    environment:
      VIRTUAL_HOST: mfnuxt.serega183.ru
      LETSENCRYPT_HOST: mfnuxt.serega183.ru
    networks:
      - nginx-proxy
    volumes:
      - .output/:/app/.output/
    ports:
      - 3000:3000
    command: ["node", "/app/.output/server/index.mjs"]

  mf_mysql:
    container_name: mf_mysql
    image: mysql:8.0.32
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mf_root_user_password
      MYSQL_DATABASE: mf_mysql_01
      MYSQL_USER: mf_user
      MYSQL_PASSWORD: mf_user_pass
    networks:
      - nginx-proxy

  mfphpmyadmin:
    container_name: mfphpmyadmin
    image: phpmyadmin:5.2.1
    environment:
      VIRTUAL_HOST: mfphpmyadmin.serega183.ru
      LETSENCRYPT_HOST: mfphpmyadmin.serega183.ru
      PMA_HOST: mf_mysql
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
