version: "3.9"
services:
  mf_nuxt:
    container_name: mf_nuxt
    image: node:18.15.0-alpine3.17
    environment:
      VIRTUAL_HOST: mfnuxt.serega183.ru
      LETSENCRYPT_HOST: mfnuxt.serega183.ru
    networks:
      - nginx-proxy
    volumes:
      - .output/:/app/.output/
    ports:
      - 3000:3000
    command: ["node", "/app/.output/server/index.mjs"]

  mf_mysql:
    container_name: mf_mysql
    image: mysql:8.0.32
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mf_root_user_password
      MYSQL_DATABASE: mf_mysql_01
      MYSQL_USER: mf_user
      MYSQL_PASSWORD: mf_user_pass
    networks:
      - nginx-proxy

  mfphpmyadmin:
    container_name: mfphpmyadmin
    image: phpmyadmin:5.2.1
    environment:
      VIRTUAL_HOST: mfphpmyadmin.serega183.ru
      LETSENCRYPT_HOST: mfphpmyadmin.serega183.ru
      PMA_HOST: mf_mysql
    networks:
      - nginx-proxy

  mf_mongo:
    image: mongo:5.0.17
    container_name: mf_mongo
    networks:
      - nginx-proxy
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb:/data/db
    environment:
      VIRTUAL_HOST: mf_mongo.local
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: test-database

  mf_mongo-express:
    image: mongo-express:0.54.0
    container_name: mf_mongo-express
    networks:
      - nginx-proxy
    ports:
      - "8081:8081"
    environment:
      VIRTUAL_HOST: mf_mongo-express.local
      ME_CONFIG_MONGODB_SERVER: mf_mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
      ME_CONFIG_MONGODB_AUTH_PASSWORD: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
