version: "3.9"
services:
  mf_nuxt:
    container_name: mf_nuxt
    build: .
    environment:
      COMANDTORUN: env NEXTAUTH_URL=http://localhost:3000 npm run dev
      VIRTUAL_HOST: mfnuxt.local
    networks:
      - nginx-proxy
    volumes:
      - .:/app
      - /node_modules
    ports:
      - 3000:3000
      - 24678:24678

  mf_mysql:
    container_name: mf_mysql
    image: mysql:8.0.32
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mf_root_user_password
      MYSQL_DATABASE: mf_mysql_01
      MYSQL_USER: mf_user
      MYSQL_PASSWORD: mf_user_pass
    networks:
      - nginx-proxy

  mfphpmyadmin:
    container_name: mfphpmyadmin
    image: phpmyadmin:5.2.1
    environment:
      VIRTUAL_HOST: mfphpmyadmin.local
      PMA_HOST: mf_mysql
    networks:
      - nginx-proxy

  mf_mongodb:
    image: mongo:5.0.17

    container_name: mf_mongodb
    networks:
      - nginx-proxy
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb/data:/data/db
      - ../mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      VIRTUAL_HOST: mf_mongo.local
      MONGO_INITDB_ROOT_USERNAME: mongoR
      MONGO_INITDB_ROOT_PASSWORD: mongoR
      MONGO_INITDB_USERNAME: mongo
      MONGO_INITDB_PASSWORD: mongo

  mf_mongo-express:
    image: mongo-express:0.54.0
    container_name: mf_mongo-express
    networks:
      - nginx-proxy
    ports:
      - "8081:8081"
    environment:
      VIRTUAL_HOST: mf_mongo-express.local
      ME_CONFIG_MONGODB_SERVER: mf_mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoR
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoR

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
